### ISSUE TITLE
PIL Import error

### ISSUE THREAD

**Issue by KrishnaPG** [cvjena/artos#2]
Below is the error when running launch 
````
cvjena-artos-79c456f\PyARTOS\GUI\MainFrame.py in <module>()
     22 
     23 import os
---> 24 from PIL import Image, ImageTk
     25 
     26 from .. import utils

ImportError: No module named PIL
````

Please check this for solution: http://stackoverflow.com/questions/8863917/importerror-no-module-named-pil

Below are the addtional locations you need to change:
````
cvjena-artos-79c456f\PyARTOS\GUI\SetupDialog.py in <module>()
     17 
     18 import os
---> 19 from .. import utils, imagenet
     20 from ..config import config
     21 
````
````
cvjena-artos-79c456f\PyARTOS\imagenet.py in <module>()
      4 from . import artos_wrapper, utils
      5 from .artos_wrapper import libartos
----> 6 from PIL import Image
      7 from glob import glob
      8 import ctypes, os.path, re, tarfile

ImportError: No module named PIL
````

**Comment by Callidior** [comment]
Note that using `import Image` seems to be a legacy way not supported by Pillow, which replaces PIL in Python 3. However, I've added a fallback in 35890ba61af0b6662e3e0864ac905f2f84bb4c7f for the case, where `from PIL import ...` does not work.

**Comment by KrishnaPG** [comment]
Thanks for the prompt response.
