### ISSUE TITLE
missing Eigen files

### ISSUE THREAD

**Issue by KrishnaPG** [cvjena/artos#3]
Below is the build error:
````
cvjena-artos-79c456f\src\ffld\HOGPyramid.h(26): fatal error C1083: Cannot open include file: 'Eigen/Core': No such file or directory
````

Looks like `Eigen` directory is missing in the source commit.

**Comment by Callidior** [comment]
Eigen *is* included under `src/ffld/Eigen`. Some include paths have to be set though, but CMake should do this automatically.
